# Generated by Django 3.1.7 on 2021-02-24 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DealtCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DiscardPile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealt_cards', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.dealtcards')),
                ('deck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.deck')),
                ('discard_pile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.discardpile')),
            ],
        ),
        migrations.CreateModel(
            name='Hand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.game')),
                ('hand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.hand')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suit', models.CharField(blank=True, max_length=2000, null=True)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('dealt_cards', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.dealtcards')),
                ('deck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.deck')),
                ('discard_pile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.discardpile')),
                ('hand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.hand')),
            ],
        ),
    ]
