# Generated by Django 3.1.7 on 2021-02-25 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='type',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
