# Generated by Django 3.1.7 on 2021-04-29 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20210419_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_state', models.IntegerField(blank=True, null=True)),
                ('hand_1_val', models.IntegerField(blank=True, null=True)),
                ('hand_1_suit', models.IntegerField(blank=True, null=True)),
                ('hand_2_val', models.IntegerField(blank=True, null=True)),
                ('hand_2_suit', models.IntegerField(blank=True, null=True)),
                ('card_1_val', models.IntegerField(blank=True, null=True)),
                ('card_1_suit', models.IntegerField(blank=True, null=True)),
                ('card_2_val', models.IntegerField(blank=True, null=True)),
                ('card_2_suit', models.IntegerField(blank=True, null=True)),
                ('card_3_val', models.IntegerField(blank=True, null=True)),
                ('card_3_suit', models.IntegerField(blank=True, null=True)),
                ('card_4_val', models.IntegerField(blank=True, null=True)),
                ('card_4_suit', models.IntegerField(blank=True, null=True)),
                ('card_5_val', models.IntegerField(blank=True, null=True)),
                ('card_5_suit', models.IntegerField(blank=True, null=True)),
                ('total_money', models.IntegerField(blank=True, null=True)),
                ('money_put', models.IntegerField(blank=True, null=True)),
                ('opp_money', models.IntegerField(blank=True, null=True)),
                ('opp_money_put', models.IntegerField(blank=True, null=True)),
                ('money_pool', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LearningModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=2000, null=True)),
                ('learning_model', models.BinaryField()),
                ('accuracy', models.FloatField()),
                ('creation_date', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='money_pool',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='small_bet',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='money_put',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='previous_choice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
