# Generated by Django 3.1.7 on 2021-05-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_learningdata_decision'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmodels',
            name='data_amount',
            field=models.IntegerField(default=0),
        ),
    ]
