# Generated by Django 3.1.7 on 2021-05-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_learningmodels_data_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningdata',
            name='money_pool',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='learningdata',
            name='money_put',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='learningdata',
            name='opp_money',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='learningdata',
            name='opp_money_put',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='learningdata',
            name='total_money',
            field=models.FloatField(default=0),
        ),
    ]
